apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-controller
  template:
    metadata:
      labels:
        app: simple-controller
    spec:
      containers:
        - name: app
          image: simple-controller:v1
      serviceAccountName: controller-sa
